import {
  Airplane01Icon,
  AlarmClockIcon,
  AlertCircleIcon,
  Apple01Icon,
  ArchiveIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Award01Icon,
  BandageIcon,
  BankIcon,
  BarChartIcon,
  BedIcon,
  BeerIcon,
  BikeIcon,
  BoatIcon,
  BookOpen01Icon,
  Briefcase01Icon,
  BulbIcon,
  Bus01Icon,
  Calendar01Icon,
  Camera01Icon,
  CancelCircleIcon,
  Car01Icon,
  Cash01Icon,
  CatIcon,
  ChartBarIncreasingIcon,
  ChartLineData01Icon,
  ChartUpIcon,
  Chat01Icon,
  CheckIcon,
  CheckmarkCircle01Icon,
  Clock01Icon,
  CloudIcon,
  Coffee01Icon,
  Compass01Icon,
  ComputerIcon,
  CpuIcon,
  CreditCardIcon,
  DashboardSpeed01Icon,
  Delete01Icon,
  Diamond01Icon,
  DrinkIcon,
  DropletsIcon,
  Dumbbell01Icon,
  EarthIcon,
  EggIcon,
  File01Icon,
  Film01Icon,
  FireIcon,
  Flag01Icon,
  FlameIcon,
  FlashIcon,
  Folder01Icon,
  FootballIcon,
  ForkIcon,
  GamepadIcon,
  GiftIcon,
  GolfBallIcon,
  GridIcon,
  HamburgerIcon,
  HammerIcon,
  HeadsetIcon,
  HeartIcon,
  HeartPulseIcon,
  Home01Icon,
  IceCream01Icon,
  InformationCircleIcon,
  Key01Icon,
  LaptopIcon,
  Layers01Icon,
  Leaf01Icon,
  LibraryIcon,
  LockIcon,
  MapPinIcon,
  MapsIcon,
  MetroIcon,
  Moon01Icon,
  MoreHorizontalIcon,
  MusicNote01Icon,
  PaintBrush01Icon,
  PencilIcon,
  PieChart01Icon,
  Pizza01Icon,
  PrinterIcon,
  Pulse01Icon,
  ReceiptTextIcon,
  RefreshIcon,
  RepeatIcon,
  RibbonIcon,
  Rocket01Icon,
  SailboatCoastalIcon,
  SchoolIcon,
  ScissorIcon,
  Search01Icon,
  ServerStack01Icon,
  Settings01Icon,
  Share01Icon,
  Shield01Icon,
  ShoppingBag01Icon,
  ShoppingBasket01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SmileIcon,
  SparklesIcon,
  StarIcon,
  Sun01Icon,
  Tablet01Icon,
  Tag01Icon,
  ThermometerIcon,
  Train01Icon,
  TShirtIcon,
  UmbrellaIcon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  WalkingIcon,
  Wallet01Icon,
  Wifi01Icon,
  Wrench01Icon,
} from '@hugeicons/core-free-icons';
import type { IconSvgElement } from '@hugeicons/react-native';
export type { IconSvgElement } from '@hugeicons/react-native';

// String type aliases for icon name strings stored in DB
export type MaterialIconName = string;
export type IoniconName = string;

export const LEGACY_ICON_MAP: Record<string, string> = {
  "accessibility-outline": "user",
  "account-group-outline": "user-group",
  "account-group-outline-dup": "user-multiple",
  "account-outline": "user",
  "alarm-outline": "alarm-clock",
  "alarm": "alarm-clock",
  "alert-circle": "alert-circle",
  "alert": "alert-circle",
  "airplane-outline": "airplane",
  "airplane": "airplane",
  "analytics-outline": "chart-line-data",
  "archive-outline": "archive",
  "arrow-down-circle-outline": "arrow-down",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "arrow-up-circle-outline": "arrow-up",
  "bag-outline": "shopping-bag",
  "bandage-outline": "bandage",
  "bandage": "bandage",
  "bar-chart-outline": "bar-chart",
  "barbell-outline": "dumbbell",
  "basket-outline": "shopping-basket",
  "bed-outline": "bed",
  "beer-outline": "beer",
  "bicycle-outline": "bike",
  "bike": "bike",
  "boat-outline": "sailboat-coastal",
  "boat": "boat",
  "book-open-page-variant-outline": "book-open",
  "book-outline": "book-open",
  "briefcase-outline": "briefcase",
  "build-outline": "wrench",
  "bus-outline": "bus",
  "bus": "bus",
  "business-outline": "building",
  "cafe-outline": "coffee",
  "calculator-outline": "bar-chart",
  "calculator": "bar-chart",
  "calendar-outline": "calendar",
  "calendar": "calendar",
  "car-outline": "car",
  "card-account-details-outline": "credit-card",
  "card-outline": "credit-card",
  "card": "credit-card",
  "cash-outline": "cash",
  "cash": "cash",
  "cellphone": "smartphone",
  "chat-outline": "chat",
  "chatbubbles-outline": "chat",
  "check-circle-outline": "checkmark-circle",
  "check-circle": "checkmark-circle",
  "check-decagram-outline": "checkmark-circle",
  "check": "check",
  "chevron-right": "arrow-right",
  "clock-outline": "clock",
  "close-circle-outline": "cancel-circle",
  "close-circle": "cancel-circle",
  "cloud-outline": "cloud",
  "cog-outline": "settings",
  "compass-outline": "compass",
  "content-cut": "scissor",
  "cpu-64-bit": "cpu",
  "creation": "sparkles",
  "cut-outline": "scissor",
  "desktop-outline": "computer",
  "diamond-outline": "diamond",
  "diamond-stone": "diamond",
  "document-text-outline": "file",
  "domain": "building",
  "dots-horizontal": "more-horizontal",
  "dots-vertical": "more-horizontal",
  "download-outline": "arrow-down",
  "earth": "earth",
  "egg-outline": "egg",
  "ellipsis-horizontal-outline": "more-horizontal",
  "emoticon-happy-outline": "smile",
  "fast-food-outline": "hamburger",
  "file-document-outline": "file",
  "film-outline": "film",
  "filmstrip": "film",
  "fitness-outline": "heart-pulse",
  "flame-outline": "flame",
  "flame": "flame",
  "flash-outline": "flash",
  "folder-outline": "folder",
  "food-apple": "apple",
  "football-outline": "football",
  "football": "football",
  "game-controller-outline": "gamepad",
  "gamepad-variant-outline": "gamepad",
  "gift-outline": "gift",
  "glass-wine": "drink",
  "globe-outline": "earth",
  "golf-outline": "golf-ball",
  "golf": "golf-ball",
  "grid-outline": "grid",
  "grid": "grid",
  "hamburger": "hamburger",
  "hammer-outline": "hammer",
  "hammer": "hammer",
  "happy-outline": "smile",
  "hardware-chip-outline": "cpu",
  "heart-circle-outline": "heart",
  "heart-outline": "heart",
  "heart-pulse": "heart-pulse",
  "home-outline": "home",
  "human-greeting": "smile",
  "human": "user",
  "ice-cream-outline": "ice-cream",
  "id-card-outline": "credit-card",
  "information-outline": "information-circle",
  "information": "information-circle",
  "key-outline": "key",
  "key": "key",
  "laptop-outline": "laptop",
  "laptop": "laptop",
  "layers-outline": "layers",
  "leaf-outline": "leaf",
  "leaf": "leaf",
  "library-outline": "library",
  "lightbulb-on-outline": "bulb",
  "lightning-bolt": "flash",
  "locate-outline": "map-pin",
  "lock-closed-outline": "lock",
  "lock-outline": "lock",
  "lock": "lock",
  "magnify": "search",
  "map-outline": "maps",
  "medical-bag": "bandage",
  "medkit-outline": "bandage",
  "monitor": "computer",
  "moon-outline": "moon",
  "moon-waning-crescent": "moon",
  "musical-notes-outline": "music-note",
  "nutrition-outline": "apple",
  "palette-outline": "paint-brush",
  "paw-outline": "cat",
  "paw": "cat",
  "pencil-outline": "pencil",
  "people-outline": "user-group",
  "person-outline": "user",
  "phone-portrait-outline": "smartphone",
  "pie-chart-outline": "pie-chart",
  "pizza-outline": "pizza",
  "pizza": "pizza",
  "plus-circle-outline": "chart-bar-increasing",
  "plus": "chart-bar-increasing",
  "print-outline": "printer",
  "printer-outline": "printer",
  "pulse-outline": "pulse",
  "receipt-outline": "receipt-text",
  "receipt-text-outline": "receipt-text",
  "refresh-outline": "refresh",
  "refresh": "refresh",
  "repeat-outline": "repeat",
  "restaurant-outline": "fork",
  "ribbon-outline": "ribbon",
  "rocket-launch-outline": "rocket",
  "rocket-outline": "rocket",
  "server-outline": "server-stack",
  "server": "server-stack",
  "share-outline": "share",
  "shield-check-outline": "shield",
  "shield-checkmark-outline": "shield",
  "shirt-outline": "t-shirt",
  "shopping-outline": "shopping-bag",
  "silverware-fork-knife": "fork",
  "sparkles-outline": "sparkles",
  "speedometer-outline": "dashboard-speed",
  "star-outline": "star",
  "stats-chart-outline": "bar-chart",
  "subway-outline": "metro",
  "sunny-outline": "sun",
  "swap-horizontal": "repeat",
  "sync": "refresh",
  "tablet-portrait-outline": "tablet",
  "tag-multiple-outline": "tag",
  "tag-outline": "tag",
  "thermometer-outline": "thermometer",
  "train-outline": "train",
  "trash-can-outline": "delete",
  "trending-up-outline": "chart-up",
  "trophy-outline": "award",
  "tshirt-crew-outline": "t-shirt",
  "umbrella-outline": "umbrella",
  "walk-outline": "walking",
  "water-outline": "droplets",
  "weight-lifter": "dumbbell",
  "wifi-outline": "wifi",
  "wine-outline": "drink",
};

export const ICON_MAP: Record<string, IconSvgElement> = {
  'airplane': Airplane01Icon,
  'alarm-clock': AlarmClockIcon,
  'alert-circle': AlertCircleIcon,
  'apple': Apple01Icon,
  'archive': ArchiveIcon,
  'arrow-down': ArrowDown01Icon,
  'arrow-left': ArrowLeft01Icon,
  'arrow-right': ArrowRight01Icon,
  'arrow-up': ArrowUp01Icon,
  'award': Award01Icon,
  'bandage': BandageIcon,
  'bar-chart': BarChartIcon,
  'bed': BedIcon,
  'beer': BeerIcon,
  'bike': BikeIcon,
  'boat': BoatIcon,
  'book-open': BookOpen01Icon,
  'briefcase': Briefcase01Icon,
  'building': BankIcon,
  'bulb': BulbIcon,
  'bus': Bus01Icon,
  'calendar': Calendar01Icon,
  'camera': Camera01Icon,
  'cancel-circle': CancelCircleIcon,
  'car': Car01Icon,
  'cash': Cash01Icon,
  'cat': CatIcon,
  'chart-bar-increasing': ChartBarIncreasingIcon,
  'chart-line-data': ChartLineData01Icon,
  'chart-up': ChartUpIcon,
  'check': CheckIcon,
  'checkmark-circle': CheckmarkCircle01Icon,
  'clock': Clock01Icon,
  'cloud': CloudIcon,
  'coffee': Coffee01Icon,
  'computer': ComputerIcon,
  'compass': Compass01Icon,
  'cpu': CpuIcon,
  'credit-card': CreditCardIcon,
  'dashboard-speed': DashboardSpeed01Icon,
  'delete': Delete01Icon,
  'diamond': Diamond01Icon,
  'drink': DrinkIcon,
  'droplets': DropletsIcon,
  'dumbbell': Dumbbell01Icon,
  'earth': EarthIcon,
  'egg': EggIcon,
  'file': File01Icon,
  'film': Film01Icon,
  'fire': FireIcon,
  'flag': Flag01Icon,
  'flame': FlameIcon,
  'flash': FlashIcon,
  'folder': Folder01Icon,
  'football': FootballIcon,
  'fork': ForkIcon,
  'gamepad': GamepadIcon,
  'gift': GiftIcon,
  'grid': GridIcon,
  'golf-ball': GolfBallIcon,
  'hamburger': HamburgerIcon,
  'hammer': HammerIcon,
  'headset': HeadsetIcon,
  'heart': HeartIcon,
  'heart-pulse': HeartPulseIcon,
  'home': Home01Icon,
  'ice-cream': IceCream01Icon,
  'information-circle': InformationCircleIcon,
  'key': Key01Icon,
  'laptop': LaptopIcon,
  'layers': Layers01Icon,
  'leaf': Leaf01Icon,
  'library': LibraryIcon,
  'lock': LockIcon,
  'map-pin': MapPinIcon,
  'maps': MapsIcon,
  'metro': MetroIcon,
  'moon': Moon01Icon,
  'more-horizontal': MoreHorizontalIcon,
  'music-note': MusicNote01Icon,
  'paint-brush': PaintBrush01Icon,
  'pencil': PencilIcon,
  'pie-chart': PieChart01Icon,
  'pizza': Pizza01Icon,
  'printer': PrinterIcon,
  'pulse': Pulse01Icon,
  'receipt-text': ReceiptTextIcon,
  'refresh': RefreshIcon,
  'repeat': RepeatIcon,
  'ribbon': RibbonIcon,
  'rocket': Rocket01Icon,
  'sailboat-coastal': SailboatCoastalIcon,
  'scissor': ScissorIcon,
  'school': SchoolIcon,
  'search': Search01Icon,
  'server-stack': ServerStack01Icon,
  'settings': Settings01Icon,
  'share': Share01Icon,
  'shield': Shield01Icon,
  'shopping-bag': ShoppingBag01Icon,
  'shopping-basket': ShoppingBasket01Icon,
  'shopping-cart': ShoppingCart01Icon,
  'smartphone': SmartPhone01Icon,
  'smile': SmileIcon,
  'sparkles': SparklesIcon,
  'star': StarIcon,
  'sun': Sun01Icon,
  'tablet': Tablet01Icon,
  'tag': Tag01Icon,
  'thermometer': ThermometerIcon,
  'train': Train01Icon,
  't-shirt': TShirtIcon,
  'umbrella': UmbrellaIcon,
  'user-group': UserGroupIcon,
  'user': UserIcon,
  'user-multiple': UserMultipleIcon,
  'walking': WalkingIcon,
  'wifi': Wifi01Icon,
  'wrench': Wrench01Icon,
  'chat': Chat01Icon,
  'wallet': Wallet01Icon,
};

/**
 * Safely resolve a string (e.g. from the database) to a valid IconSvgElement.
 * Returns the fallback when the stored value is not a recognised icon key.
 */
export function resolveIcon(
  icon: string | null | undefined,
  fallback: IconSvgElement,
): IconSvgElement {
  if (!icon) return fallback;
  const resolvedKey = LEGACY_ICON_MAP[icon] || icon;
  return ICON_MAP[resolvedKey] || fallback;
}

import type { AccountType } from '@/src/types';

export const ACCOUNT_TYPE_ICON_MAP: Record<AccountType, IconSvgElement> = {
  cash: ICON_MAP['cash']!,
  bank: ICON_MAP['building']!,
  savings: ICON_MAP['diamond']!,
  credit_card: ICON_MAP['credit-card']!,
  investment: ICON_MAP['chart-line-data']!,
  loan: ICON_MAP['receipt-text']!,
  ewallet: ICON_MAP['wallet']!,
};

export function resolveAccountTypeIcon(
  accountType: AccountType | null | undefined,
): IconSvgElement {
  if (!accountType) return ICON_MAP['building']!;
  return ACCOUNT_TYPE_ICON_MAP[accountType] ?? ICON_MAP['building']!;
}
