import {
  Airplane01Icon,
  AlarmClockIcon,
  AlertCircleIcon,
  Apple01Icon,
  ArchiveIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Award01Icon,
  BandageIcon,
  BarChartIcon,
  BedIcon,
  BeerIcon,
  BikeIcon,
  BoatIcon,
  BookOpen01Icon,
  Briefcase01Icon,
  Building01Icon,
  BulbIcon,
  Bus01Icon,
  Calendar01Icon,
  Camera01Icon,
  CancelCircleIcon,
  Car01Icon,
  Cash01Icon,
  CatIcon,
  ChartBarIncreasingIcon,
  ChartLineData01Icon,
  ChartUpIcon,
  CheckIcon,
  CheckmarkCircle01Icon,
  Clock01Icon,
  CloudIcon,
  Coffee01Icon,
  ComputerIcon,
  Compass01Icon,
  CpuIcon,
  CreditCardIcon,
  DashboardSpeed01Icon,
  Delete01Icon,
  Diamond01Icon,
  DrinkIcon,
  DropletsIcon,
  Dumbbell01Icon,
  EarthIcon,
  EggIcon,
  File01Icon,
  Film01Icon,
  FireIcon,
  Flag01Icon,
  FlameIcon,
  FlashIcon,
  Folder01Icon,
  FootballIcon,
  ForkIcon,
  GamepadIcon,
  GiftIcon,
  GridIcon,
  GolfBallIcon,
  HamburgerIcon,
  HammerIcon,
  HeadsetIcon,
  HeartIcon,
  HeartPulseIcon,
  Home01Icon,
  IceCream01Icon,
  InformationCircleIcon,
  Key01Icon,
  LaptopIcon,
  Layers01Icon,
  Leaf01Icon,
  LibraryIcon,
  LockIcon,
  MapPinIcon,
  MapsIcon,
  MetroIcon,
  Moon01Icon,
  MoreHorizontalIcon,
  MusicNote01Icon,
  PaintBrush01Icon,
  PencilIcon,
  PieChart01Icon,
  Pizza01Icon,
  PrinterIcon,
  Pulse01Icon,
  ReceiptTextIcon,
  RefreshIcon,
  RepeatIcon,
  RibbonIcon,
  Rocket01Icon,
  SailboatCoastalIcon,
  ScissorIcon,
  SchoolIcon,
  Search01Icon,
  ServerStack01Icon,
  Settings01Icon,
  Share01Icon,
  Shield01Icon,
  ShoppingBag01Icon,
  ShoppingBasket01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SmileIcon,
  SparklesIcon,
  StarIcon,
  Sun01Icon,
  Tablet01Icon,
  Tag01Icon,
  ThermometerIcon,
  Train01Icon,
  TShirtIcon,
  UmbrellaIcon,
  UserGroupIcon,
  UserIcon,
  UserMultipleIcon,
  WalkingIcon,
  Wifi01Icon,
  Wrench01Icon,
  Chat01Icon,
  Wallet01Icon,
} from '@hugeicons/core-free-icons';
import type { IconSvgElement } from '@hugeicons/react-native';
export type { IconSvgElement } from '@hugeicons/react-native';

// String type aliases for icon name strings stored in DB
export type MaterialIconName = string;
export type IoniconName = string;

// Legacy map: old Ionicons names → current ICON_MAP keys (used by DB migrations)
export const LEGACY_ICON_MAP: Record<string, string> = {
  "wallet-outline": "wallet-outline",
  "card-outline": "card-outline",
  "cash-outline": "cash",
  "receipt-outline": "receipt-text-outline",
  "document-text-outline": "file-document-outline",
  "shield-checkmark-outline": "shield-check-outline",
  "key-outline": "key-outline",
  "lock-closed-outline": "lock-outline",
  "id-card-outline": "card-account-details-outline",
  "diamond-outline": "diamond-stone",
  "trending-up-outline": "trending-up",
  "stats-chart-outline": "chart-bar",
  "pie-chart-outline": "chart-pie",
  "analytics-outline": "chart-timeline-variant",
  "layers-outline": "layers-outline",
  "bar-chart-outline": "chart-bar",
  "rocket-outline": "rocket-launch-outline",
  "pulse-outline": "heart-pulse",
  "briefcase-outline": "briefcase-outline",
  "business-outline": "domain",
  "server-outline": "server",
  "laptop-outline": "laptop",
  "archive-outline": "archive-outline",
  "calculator-outline": "calculator",
  "desktop-outline": "monitor",
  "print-outline": "printer-outline",
  "home-outline": "home-outline",
  "car-outline": "car-outline",
  "airplane-outline": "airplane",
  "heart-outline": "heart-outline",
  "school-outline": "school-outline",
  "trophy-outline": "trophy-outline",
  "flag-outline": "flag-outline",
  "compass-outline": "compass-outline",
  "phone-portrait-outline": "cellphone",
  "globe-outline": "earth",
  "people-outline": "account-group-outline",
  "leaf-outline": "leaf",
  "gift-outline": "gift-outline",
  "star-outline": "star-outline",
  "moon-outline": "moon-waning-crescent",
  "sunny-outline": "weather-sunny",
  "cog-outline": "cog-outline",
  "hammer-outline": "hammer",
  "flash-outline": "flash-outline",
  "water-outline": "water-outline",
  "refresh-outline": "refresh",
  "fast-food-outline": "hamburger",
  "restaurant-outline": "silverware-fork-knife",
  "cafe-outline": "coffee-outline",
  "pizza-outline": "pizza",
  "wine-outline": "glass-wine",
  "beer-outline": "beer-outline",
  "ice-cream-outline": "ice-cream",
  "basket-outline": "basket-outline",
  "nutrition-outline": "food-apple",
  "egg-outline": "egg-outline",
  "bus-outline": "bus",
  "train-outline": "train",
  "bicycle-outline": "bike",
  "boat-outline": "sail-boat",
  "speedometer-outline": "speedometer",
  "locate-outline": "crosshairs-gps",
  "walk-outline": "walk",
  "subway-outline": "subway",
  "wifi-outline": "wifi",
  "build-outline": "wrench-outline",
  "bed-outline": "bed-outline",
  "thermometer-outline": "thermometer",
  "flame-outline": "fire",
  "medkit-outline": "medical-bag",
  "bandage-outline": "bandage",
  "barbell-outline": "barbell-outline",
  "fitness-outline": "heart-pulse",
  "accessibility-outline": "human",
  "body-outline": "human",
  "hardware-chip-outline": "cpu-64-bit",
  "tablet-portrait-outline": "tablet",
  "headset-outline": "headset",
  "bag-outline": "shopping-outline",
  "repeat-outline": "repeat",
  "cut-outline": "content-cut",
  "shirt-outline": "tshirt-crew-outline",
  "film-outline": "filmstrip",
  "game-controller-outline": "gamepad-variant-outline",
  "musical-notes-outline": "music-note",
  "color-palette-outline": "palette-outline",
  "book-outline": "book-open-page-variant-outline",
  "football-outline": "football",
  "golf-outline": "golf",
  "library-outline": "library",
  "pencil-outline": "pencil-outline",
  "person-outline": "account-outline",
  "happy-outline": "emoticon-happy-outline",
  "paw-outline": "paw",
  "heart-circle-outline": "heart-circle-outline",
  "ribbon-outline": "ribbon",
  "chatbubbles-outline": "chat-outline",
  "sparkles-outline": "creation",
  "bulb-outline": "lightbulb-on-outline",
  "grid-outline": "grid-outline",
  "ellipsis-horizontal-outline": "dots-horizontal",
  "time-outline": "clock-outline",
  "alarm-outline": "alarm",
  "calendar-outline": "calendar-outline",
  "map-outline": "map-outline",
};

export const ICON_MAP: Record<string, IconSvgElement> = {
  // Account picker icons (MaterialCommunityIcons keys)
  'wallet-outline': Wallet01Icon,
  'card-outline': CreditCardIcon,
  'cash': Cash01Icon,
  'receipt-text-outline': ReceiptTextIcon,
  'file-document-outline': File01Icon,
  'shield-check-outline': Shield01Icon,
  'key-outline': Key01Icon,
  'lock-outline': LockIcon,
  'card-account-details-outline': CreditCardIcon,
  'diamond-stone': Diamond01Icon,
  'trending-up': ChartUpIcon,
  'chart-bar': BarChartIcon,
  'chart-pie': PieChart01Icon,
  'chart-timeline-variant': ChartLineData01Icon,
  'layers-outline': Layers01Icon,
  'rocket-launch-outline': Rocket01Icon,
  'heart-pulse': HeartPulseIcon,
  'briefcase-outline': Briefcase01Icon,
  'domain': Building01Icon,
  'server': ServerStack01Icon,
  'laptop': LaptopIcon,
  'archive-outline': ArchiveIcon,
  'calculator': BarChartIcon,
  'monitor': ComputerIcon,
  'printer-outline': PrinterIcon,
  'home-outline': Home01Icon,
  'car-outline': Car01Icon,
  'airplane': Airplane01Icon,
  'heart-outline': HeartIcon,
  'school-outline': SchoolIcon,
  'trophy-outline': Award01Icon,
  'flag-outline': Flag01Icon,
  'compass-outline': Compass01Icon,
  'cellphone': SmartPhone01Icon,
  'earth': EarthIcon,
  'account-group-outline': UserGroupIcon,
  'leaf': Leaf01Icon,
  'gift-outline': GiftIcon,
  'star-outline': StarIcon,
  'moon-waning-crescent': Moon01Icon,
  'weather-sunny': Sun01Icon,
  'cog-outline': Settings01Icon,
  'hammer': HammerIcon,
  'flash-outline': FlashIcon,
  'water-outline': DropletsIcon,
  'refresh': RefreshIcon,
  // Category picker icons
  'hamburger': HamburgerIcon,
  'silverware-fork-knife': ForkIcon,
  'coffee-outline': Coffee01Icon,
  'pizza': Pizza01Icon,
  'glass-wine': DrinkIcon,
  'beer-outline': BeerIcon,
  'ice-cream': IceCream01Icon,
  'basket-outline': ShoppingBasket01Icon,
  'food-apple': Apple01Icon,
  'egg-outline': EggIcon,
  'bus': Bus01Icon,
  'train': Train01Icon,
  'bike': BikeIcon,
  'sail-boat': SailboatCoastalIcon,
  'speedometer': DashboardSpeed01Icon,
  'crosshairs-gps': MapPinIcon,
  'walk': WalkingIcon,
  'subway': MetroIcon,
  'wifi': Wifi01Icon,
  'wrench-outline': Wrench01Icon,
  'bed-outline': BedIcon,
  'thermometer': ThermometerIcon,
  'fire': FireIcon,
  'medical-bag': BandageIcon,
  'bandage': BandageIcon,
  'weight-lifter': Dumbbell01Icon,
  'pulse-outline': Pulse01Icon,
  'human': UserIcon,
  'human-greeting': SmileIcon,
  'cpu-64-bit': CpuIcon,
  'tablet': Tablet01Icon,
  'headset': HeadsetIcon,
  'cloud-outline': CloudIcon,
  'shopping-outline': ShoppingBag01Icon,
  'cart-outline': ShoppingCart01Icon,
  'repeat': RepeatIcon,
  'content-cut': ScissorIcon,
  'umbrella-outline': UmbrellaIcon,
  'tshirt-crew-outline': TShirtIcon,
  'filmstrip': Film01Icon,
  'gamepad-variant-outline': GamepadIcon,
  'music-note': MusicNote01Icon,
  'camera-outline': Camera01Icon,
  'palette-outline': PaintBrush01Icon,
  'book-open-page-variant-outline': BookOpen01Icon,
  'football': FootballIcon,
  'golf': GolfBallIcon,
  'library': LibraryIcon,
  'pencil-outline': PencilIcon,
  'account-outline': UserIcon,
  'emoticon-happy-outline': SmileIcon,
  'paw': CatIcon,
  'heart-circle-outline': HeartIcon,
  'ribbon': RibbonIcon,
  'chat-outline': Chat01Icon,
  'creation': SparklesIcon,
  'lightbulb-on-outline': BulbIcon,
  'grid': GridIcon,
  'grid-outline': GridIcon,
  'dots-horizontal': MoreHorizontalIcon,
  'clock-outline': Clock01Icon,
  'alarm': AlarmClockIcon,
  'calendar-outline': Calendar01Icon,
  'map-outline': MapsIcon,
  'tag-outline': Tag01Icon,
  // UI icons
  'arrow-left': ArrowLeft01Icon,
  'arrow-right': ArrowRight01Icon,
  'check': CheckIcon,
  'check-circle': CheckmarkCircle01Icon,
  'check-circle-outline': CheckmarkCircle01Icon,
  'close-circle': CancelCircleIcon,
  'close-circle-outline': CancelCircleIcon,
  'chevron-right': ArrowRight01Icon,
  'magnify': Search01Icon,
  'information': InformationCircleIcon,
  'information-outline': InformationCircleIcon,
  'alert-circle': AlertCircleIcon,
  'alert': AlertCircleIcon,
  'calendar': Calendar01Icon,
  'folder-outline': Folder01Icon,
  'share-outline': Share01Icon,
  'trash-can-outline': Delete01Icon,
  'lightning-bolt': FlashIcon,
  'plus-circle-outline': ChartBarIncreasingIcon,
  'arrow-down-circle-outline': ArrowDown01Icon,
  'arrow-up-circle-outline': ArrowUp01Icon,
  'swap-horizontal': RepeatIcon,
  'sync': RefreshIcon,
  'check-decagram-outline': CheckmarkCircle01Icon,
  'flame': FlameIcon,
  // Additional icons referenced in the codebase
  'boat': BoatIcon,
  'dots-vertical': MoreHorizontalIcon,
  'download-outline': ArrowDown01Icon,
  'lock': LockIcon,
  'plus': ChartBarIncreasingIcon,
  'account-group-outline-dup': UserMultipleIcon,
  'tag-multiple-outline': Tag01Icon,
  // Legacy Ionicons keys
  'card-outline-ionicon': CreditCardIcon,
  'cash-outline': Cash01Icon,
  'receipt-outline': ReceiptTextIcon,
  'document-text-outline': File01Icon,
  'shield-checkmark-outline': Shield01Icon,
  'id-card-outline': CreditCardIcon,
  'diamond-outline': Diamond01Icon,
  'trending-up-outline': ChartUpIcon,
  'stats-chart-outline': BarChartIcon,
  'pie-chart-outline': PieChart01Icon,
  'analytics-outline': ChartLineData01Icon,
  'bar-chart-outline': BarChartIcon,
  'rocket-outline': Rocket01Icon,
  'pulse-outline-ionicon': HeartPulseIcon,
  'business-outline': Building01Icon,
  'server-outline': ServerStack01Icon,
  'laptop-outline': LaptopIcon,
  'calculator-outline': BarChartIcon,
  'desktop-outline': ComputerIcon,
  'print-outline': PrinterIcon,
  'airplane-outline': Airplane01Icon,
  'phone-portrait-outline': SmartPhone01Icon,
  'globe-outline': EarthIcon,
  'people-outline': UserGroupIcon,
  'leaf-outline': Leaf01Icon,
  'star-outline-ionicon': StarIcon,
  'moon-outline': Moon01Icon,
  'sunny-outline': Sun01Icon,
  'hammer-outline': HammerIcon,
  'water-outline-ionicon': DropletsIcon,
  'refresh-outline': RefreshIcon,
  'fast-food-outline': HamburgerIcon,
  'restaurant-outline': ForkIcon,
  'cafe-outline': Coffee01Icon,
  'pizza-outline': Pizza01Icon,
  'wine-outline': DrinkIcon,
  'ice-cream-outline': IceCream01Icon,
  'nutrition-outline': Apple01Icon,
  'bus-outline': Bus01Icon,
  'train-outline': Train01Icon,
  'bicycle-outline': BikeIcon,
  'boat-outline': SailboatCoastalIcon,
  'speedometer-outline': DashboardSpeed01Icon,
  'locate-outline': MapPinIcon,
  'walk-outline': WalkingIcon,
  'subway-outline': MetroIcon,
  'wifi-outline': Wifi01Icon,
  'build-outline': Wrench01Icon,
  'thermometer-outline': ThermometerIcon,
  'flame-outline': FireIcon,
  'medkit-outline': BandageIcon,
  'bandage-outline': BandageIcon,
  'barbell-outline': Dumbbell01Icon,
  'fitness-outline': HeartPulseIcon,
  'accessibility-outline': UserIcon,
  'body-outline': UserIcon,
  'hardware-chip-outline': CpuIcon,
  'tablet-portrait-outline': Tablet01Icon,
  'headset-outline': HeadsetIcon,
  'bag-outline': ShoppingBag01Icon,
  'repeat-outline': RepeatIcon,
  'cut-outline': ScissorIcon,
  'shirt-outline': TShirtIcon,
  'film-outline': Film01Icon,
  'game-controller-outline': GamepadIcon,
  'musical-notes-outline': MusicNote01Icon,
  'color-palette-outline': PaintBrush01Icon,
  'book-outline': BookOpen01Icon,
  'football-outline': FootballIcon,
  'golf-outline': GolfBallIcon,
  'library-outline': LibraryIcon,
  'person-outline': UserIcon,
  'happy-outline': SmileIcon,
  'paw-outline': CatIcon,
  'ribbon-outline': RibbonIcon,
  'chatbubbles-outline': Chat01Icon,
  'sparkles-outline': SparklesIcon,
  'bulb-outline': BulbIcon,
  'ellipsis-horizontal-outline': MoreHorizontalIcon,
  'time-outline': Clock01Icon,
  'alarm-outline': AlarmClockIcon,
  'map-outline-ionicon': MapsIcon,
};

/**
 * Safely resolve a string (e.g. from the database) to a valid IconSvgElement.
 * Returns the fallback when the stored value is not a recognised icon key.
 */
export function resolveIcon(
  icon: string | null | undefined,
  fallback: IconSvgElement,
): IconSvgElement {
  if (!icon) return fallback;

  if (icon in ICON_MAP) {
    return ICON_MAP[icon];
  }

  // Try with -outline suffix stripped
  const withoutOutline = icon.endsWith('-outline') ? icon.slice(0, -8) : null;
  if (withoutOutline && withoutOutline in ICON_MAP) {
    return ICON_MAP[withoutOutline];
  }

  return fallback;
}
