export const BackspaceIcon: import('@hugeicons/react-native').IconSvgElement = [
  [
    'path',
    {
      d: 'M22 12C22 8.22876 22 6.34315 20.8284 5.17157C19.6569 4 17.7712 4 14 4H11C9.03719 4 8.05571 4 7.21115 4.42229C6.36659 4.84458 5.77772 5.62972 4.6 7.2C2.86667 9.51111 2 10.6667 2 12C2 13.3333 2.86667 14.4889 4.6 16.8C5.77772 18.3703 6.36659 19.1554 7.21115 19.5777C8.05571 20 9.03719 20 11 20H14C17.7712 20 19.6569 20 20.8284 18.8284C22 17.6569 22 15.7712 22 12Z',
      stroke: 'currentColor',
      strokeWidth: '1.5',
      key: '0',
    },
  ],
  ['path', { d: 'M16.5 9.5L11.5 14.5M11.5 9.5L16.5 14.5', stroke: 'currentColor', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: '1.5', key: '1' }],
];

// The app's UI icon vocabulary — Hugeicons (the app's single icon pack).
// Semantic names (e.g. MagnifyingGlassIcon) map to the Hugeicons glyph used
// everywhere, so swapping a glyph app-wide is a one-line change here.
// Category & account icons stored in the database resolve via src/utils/icons.ts.

import type { IconSvgElement } from '@hugeicons/react-native';

import { 
  AlarmClockIcon,
  AndroidIcon,
  Apple01Icon,
  ArrowDownLeft01Icon,
  ArrowRight02Icon,
  ArrowUpRight01Icon,
  RefreshIcon,
  ArrowDataTransferHorizontalIcon,
  BankIcon,
  Notification01Icon,
  NotificationSquareIcon,
  NotificationOff01Icon,
  Briefcase01Icon,
  Calculator01Icon,
  Calendar03Icon,
  Car01Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  BarChartIcon,
  PieChart01Icon,
  CheckmarkCircle02Icon,
  Tick02Icon,
  ContrastIcon,
  Clock01Icon,
  CloudUploadIcon,
  CloudIcon,
  Coffee01Icon,
  Coins01Icon,
  Copy01Icon,
  Wallet04Icon,
  WalletCardsIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  Download01Icon,
  Share01Icon,
  File01Icon,
  FlaskConicalIcon,
  FolderOpenIcon,
  Restaurant01Icon,
  Settings01Icon,
  Globe02Icon,
  MoneyExchange01Icon,
  Cursor01Icon,
  TouchInteraction01Icon,
  Home01Icon,
  Home05Icon,
  Wallet03Icon,
  Analytics01Icon,
  Settings02Icon,
  InformationCircleIcon,
  FlashIcon,
  LockPasswordIcon,
  Search01Icon,
  Moon02Icon,
  PaintBoardIcon,
  PinCodeIcon,
  PencilEdit01Icon,
  PiggyBankIcon,
  PlusSignIcon,
  Invoice03Icon,
  CheckmarkBadge01Icon,
  ShieldKeyIcon,
  ShoppingBag01Icon,
  FilterHorizontalIcon,
  SparklesIcon,
  GridViewIcon,
  Sun03Icon,
  Tag01Icon,
  TranslateIcon,
  Delete02Icon,
  ArrowUp01Icon,
  UserCircleIcon,
  UserIcon,
  UserGroupIcon,
  Wallet01Icon,
  AlertCircleIcon,
  Alert02Icon,
  CancelCircleIcon,
  Cancel01Icon,
  Airplane01Icon,
  ArchiveIcon,
  Award01Icon,
  BandageIcon,
  BedIcon,
  BeerIcon,
  BikeIcon,
  BoatIcon,
  BookOpen01Icon,
  Building03Icon,
  BulbIcon,
  Bus01Icon,
  Camera01Icon,
  Cash01Icon,
  CatIcon,
  ChartBarIncreasingIcon,
  ChartLineData01Icon,
  ChartUpIcon,
  CheckIcon,
  CheckmarkCircle01Icon,
  ComputerIcon,
  Compass01Icon,
  CpuIcon,
  CreditCardIcon,
  DashboardSpeed01Icon,
  Delete01Icon,
  Diamond01Icon,
  DrinkIcon,
  DropletsIcon,
  Dumbbell01Icon,
  EarthIcon,
  EggIcon,
  Film01Icon,
  FireIcon,
  Flag01Icon,
  FlameIcon,
  Folder01Icon,
  FootballIcon,
  ForkIcon,
  GamepadIcon,
  GiftIcon,
  GridIcon,
  GolfBallIcon,
  HamburgerIcon,
  HammerIcon,
  HeadsetIcon,
  HeartIcon,
  HeartPulseIcon,
  IceCream01Icon,
  Key01Icon,
  LaptopIcon,
  Layers01Icon,
  Leaf01Icon,
  LibraryIcon,
  LockIcon,
  MapPinIcon,
  MapsIcon,
  MetroIcon,
  Moon01Icon,
  MusicNote01Icon,
  PaintBrush01Icon,
  PencilIcon,
  Pizza01Icon,
  PrinterIcon,
  Pulse01Icon,
  ReceiptTextIcon,
  RepeatIcon,
  RibbonIcon,
  Rocket01Icon,
  SailboatCoastalIcon,
  ScissorIcon,
  SchoolIcon,
  ServerStack01Icon,
  Shield01Icon,
  ShoppingBasket01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SmileIcon,
  StarIcon,
  Sun01Icon,
  Tablet01Icon,
  ThermometerIcon,
  Train01Icon,
  TShirtIcon,
  UmbrellaIcon,
  UserMultipleIcon,
  WalkingIcon,
  Wifi01Icon,
  Wrench01Icon,
  Chat01Icon
, NoteIcon, FilterIcon, SortingDownIcon, BatteryCharging01Icon } from '@hugeicons/core-free-icons';

export const UI_ICONS = {
  AlarmIcon: AlarmClockIcon,
  AndroidLogoIcon: AndroidIcon,
  AppleLogoIcon: Apple01Icon,
  ArrowDownLeftIcon: ArrowDownLeft01Icon,
  ArrowRightIcon: ArrowRight02Icon,
  ArrowUpRightIcon: ArrowUpRight01Icon,
  ArrowsClockwiseIcon: RefreshIcon,
  ArrowsLeftRightIcon: ArrowDataTransferHorizontalIcon,
  BankIcon: BankIcon,
  BellIcon: Notification01Icon,
  BellRingingIcon: NotificationSquareIcon,
  BellSlashIcon: NotificationOff01Icon,
  BriefcaseIcon: Briefcase01Icon,
  CalculatorIcon: Calculator01Icon,
  CalendarBlankIcon: Calendar03Icon,
  CarIcon: Car01Icon,
  CaretDownIcon: ArrowDown01Icon,
  CaretLeftIcon: ArrowLeft01Icon,
  CaretRightIcon: ArrowRight01Icon,
  ChartBarIcon: BarChartIcon,
  ChartPieSliceIcon: PieChart01Icon,
  CheckCircleIcon: CheckmarkCircle02Icon,
  CheckIcon: Tick02Icon,
  CircleHalfIcon: ContrastIcon,
  ClockIcon: Clock01Icon,
  CloudArrowUpIcon: CloudUploadIcon,
  CoffeeIcon: Coffee01Icon,
  CoinsIcon: Coins01Icon,
  CopyIcon: Copy01Icon,
  Wallet04Icon: Wallet04Icon,
  WalletCardsIcon: WalletCardsIcon,
  DotsThreeIcon: MoreHorizontalIcon,
  DotsThreeVerticalIcon: MoreVerticalIcon,
  DownloadSimpleIcon: Download01Icon,
  ExportIcon: Share01Icon,
  FileTextIcon: File01Icon,
  FlaskIcon: FlaskConicalIcon,
  FolderOpenIcon: FolderOpenIcon,
  ForkKnifeIcon: Restaurant01Icon,
  GearIcon: Settings01Icon,
  GlobeIcon: Globe02Icon,
  HandCoinsIcon: MoneyExchange01Icon,
  HandSwipeLeftIcon: Cursor01Icon,
  HandTapIcon: TouchInteraction01Icon,
  HouseIcon: Home01Icon,
  TabHomeIcon: Home05Icon,
  TabAccountsIcon: Wallet03Icon,
  TabAnalyticsIcon: Analytics01Icon,
  TabSettingsIcon: Settings02Icon,
  InfoIcon: InformationCircleIcon,
  LightningIcon: FlashIcon,
  LockKeyIcon: LockPasswordIcon,
  MagnifyingGlassIcon: Search01Icon,
  MoonIcon: Moon02Icon,
  PaletteIcon: PaintBoardIcon,
  PasswordIcon: PinCodeIcon,
  PencilSimpleIcon: PencilEdit01Icon,
  PlusIcon: PlusSignIcon,
  ReceiptIcon: Invoice03Icon,
  SealCheckIcon: CheckmarkBadge01Icon,
  ShieldCheckIcon: ShieldKeyIcon,
  ShoppingBagIcon: ShoppingBag01Icon,
  SlidersHorizontalIcon: FilterHorizontalIcon,
  SparkleIcon: SparklesIcon,
  SquaresFourIcon: GridViewIcon,
  SunIcon: Sun03Icon,
  TagIcon: Tag01Icon,
  TranslateIcon: TranslateIcon,
  TrashIcon: Delete02Icon,
  TrendDownIcon: ArrowDown01Icon,
  TrendUpIcon: ArrowUp01Icon,
  UserCircleIcon: UserCircleIcon,
  UsersIcon: UserGroupIcon,
  WalletIcon: Wallet01Icon,
  WarningCircleIcon: AlertCircleIcon,
  WarningIcon: Alert02Icon,
  XCircleIcon: CancelCircleIcon,
  XIcon: Cancel01Icon,
  AlarmClockIcon: AlarmClockIcon,
  AlertCircleIcon: AlertCircleIcon,
  Apple01Icon: Apple01Icon,
  ArrowDown01Icon: ArrowDown01Icon,
  ArrowLeft01Icon: ArrowLeft01Icon,
  ArrowUp01Icon: ArrowUp01Icon,
  BarChartIcon: BarChartIcon,
  Briefcase01Icon: Briefcase01Icon,
  CancelCircleIcon: CancelCircleIcon,
  Car01Icon: Car01Icon,
  Clock01Icon: Clock01Icon,
  Coffee01Icon: Coffee01Icon,
  File01Icon: File01Icon,
  FlashIcon: FlashIcon,
  Home01Icon: Home01Icon,
  InformationCircleIcon: InformationCircleIcon,
  MoreHorizontalIcon: MoreHorizontalIcon,
  PieChart01Icon: PieChart01Icon,
  RefreshIcon: RefreshIcon,
  Search01Icon: Search01Icon,
  Settings01Icon: Settings01Icon,
  Share01Icon: Share01Icon,
  ShoppingBag01Icon: ShoppingBag01Icon,
  SparklesIcon: SparklesIcon,
  Tag01Icon: Tag01Icon,
  UserGroupIcon: UserGroupIcon,
  Wallet01Icon: Wallet01Icon,
  Airplane01Icon: Airplane01Icon,
  ArchiveIcon: ArchiveIcon,
  Award01Icon: Award01Icon,
  BandageIcon: BandageIcon,
  BedIcon: BedIcon,
  BeerIcon: BeerIcon,
  BikeIcon: BikeIcon,
  BoatIcon: BoatIcon,
  BookOpen01Icon: BookOpen01Icon,
  Building03Icon: Building03Icon,
  BulbIcon: BulbIcon,
  Bus01Icon: Bus01Icon,
  Camera01Icon: Camera01Icon,
  Cash01Icon: Cash01Icon,
  CatIcon: CatIcon,
  ChartBarIncreasingIcon: ChartBarIncreasingIcon,
  ChartLineData01Icon: ChartLineData01Icon,
  ChartUpIcon: ChartUpIcon,
  CheckmarkCircle01Icon: CheckmarkCircle01Icon,
  CloudIcon: CloudIcon,
  ComputerIcon: ComputerIcon,
  Compass01Icon: Compass01Icon,
  CpuIcon: CpuIcon,
  CreditCardIcon: CreditCardIcon,
  DashboardSpeed01Icon: DashboardSpeed01Icon,
  Delete01Icon: Delete01Icon,
  Diamond01Icon: Diamond01Icon,
  DrinkIcon: DrinkIcon,
  DropletsIcon: DropletsIcon,
  Dumbbell01Icon: Dumbbell01Icon,
  EarthIcon: EarthIcon,
  EggIcon: EggIcon,
  Film01Icon: Film01Icon,
  FireIcon: FireIcon,
  Flag01Icon: Flag01Icon,
  FlameIcon: FlameIcon,
  Folder01Icon: Folder01Icon,
  FootballIcon: FootballIcon,
  ForkIcon: ForkIcon,
  GamepadIcon: GamepadIcon,
  GiftIcon: GiftIcon,
  GridIcon: GridIcon,
  GolfBallIcon: GolfBallIcon,
  HamburgerIcon: HamburgerIcon,
  HammerIcon: HammerIcon,
  HeadsetIcon: HeadsetIcon,
  HeartIcon: HeartIcon,
  HeartPulseIcon: HeartPulseIcon,
  IceCream01Icon: IceCream01Icon,
  Key01Icon: Key01Icon,
  LaptopIcon: LaptopIcon,
  Layers01Icon: Layers01Icon,
  Leaf01Icon: Leaf01Icon,
  LibraryIcon: LibraryIcon,
  LockIcon: LockIcon,
  MapPinIcon: MapPinIcon,
  MapsIcon: MapsIcon,
  MetroIcon: MetroIcon,
  Moon01Icon: Moon01Icon,
  MusicNote01Icon: MusicNote01Icon,
  PaintBrush01Icon: PaintBrush01Icon,
  PencilIcon: PencilIcon,
  Pizza01Icon: Pizza01Icon,
  PrinterIcon: PrinterIcon,
  Pulse01Icon: Pulse01Icon,
  ReceiptTextIcon: ReceiptTextIcon,
  RepeatIcon: RepeatIcon,
  RibbonIcon: RibbonIcon,
  Rocket01Icon: Rocket01Icon,
  SailboatCoastalIcon: SailboatCoastalIcon,
  ScissorIcon: ScissorIcon,
  SchoolIcon: SchoolIcon,
  ServerStack01Icon: ServerStack01Icon,
  Shield01Icon: Shield01Icon,
  ShoppingBasket01Icon: ShoppingBasket01Icon,
  ShoppingCart01Icon: ShoppingCart01Icon,
  SmartPhone01Icon: SmartPhone01Icon,
  SmileIcon: SmileIcon,
  StarIcon: StarIcon,
  Sun01Icon: Sun01Icon,
  Tablet01Icon: Tablet01Icon,
  ThermometerIcon: ThermometerIcon,
  Train01Icon: Train01Icon,
  TShirtIcon: TShirtIcon,
  UmbrellaIcon: UmbrellaIcon,
  UserIcon: UserIcon,
  UserMultipleIcon: UserMultipleIcon,
  WalkingIcon: WalkingIcon,
  Wifi01Icon: Wifi01Icon,
  Wrench01Icon: Wrench01Icon,
  Chat01Icon: Chat01Icon,
  PiggyBankIcon: PiggyBankIcon,
  BackspaceIcon,
  NoteIcon: NoteIcon,
  FilterIcon: FilterIcon,
  SortingDownIcon: SortingDownIcon,
  BatteryCharging01Icon: BatteryCharging01Icon
};




export type IconName = keyof typeof UI_ICONS | (string & {});
